---
version: "3"
services:
  nginx:
    container_name: nginx
    image: nginx:stable
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/ssl:ro
    ports:
      - "80:80"
      - "443:443"
...
